source 'http://rubygems.org'

RAILS_VERSION = '~> 3.0.3'

### Rails ###
gem 'actionmailer',   RAILS_VERSION, :require => 'action_mailer'
gem 'actionpack',     RAILS_VERSION, :require => 'action_pack'
gem 'activerecord',   RAILS_VERSION, :require => 'active_record'
gem 'activeresource', RAILS_VERSION, :require => 'active_resource'
gem 'activesupport',  RAILS_VERSION, :require => 'active_support'
gem 'railties',       RAILS_VERSION, :require => 'rails'

gem 'sqlite3-ruby', :require => 'sqlite3'

### Application Gems ###

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  ### Rails Generators ###
end ### dev/test group ###
